<?php
$form = $this->uploadForm;
$form->setAttribute('action', $this->url('application/default', array('controller'=>'index',
                                 'action' => 'form')));
$form->setAttribute('id', 'frmUpload');
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class="form-group">
    <label class="sr-only" for="">Fridge (*.csv)</label>
    <?php echo $this->formRow(
        $form->get('csv')
            ->setAttribute('class', 'form-control')
    ); ?>
</div>

<?php if ($csv===false):?>
<div class="alert alert-warning" role="alert">No Fridge.csv</div>
<?php else: ?>
<div class="panel panel-default js-uploaded-file">
    <div class="panel-heading">Fridge.csv</div>
    <div class="panel-body"><pre><?php echo $csv;?></pre></div>
</div>
<?php endif;?>

<div class="form-group">
    <label class="sr-only" for="">Recipes (*.json)</label>
    <?php echo $this->formRow(
        $form->get('json')
            ->setAttribute('class', 'form-control')
    ); ?>
</div>

<?php if ($json===false):?>
    <div class="alert alert-warning" role="alert">No Recipes.json</div>
<?php else: ?>
    <div class="panel panel-default js-uploaded-file">
        <div class="panel-heading">Recipes.json</div>
        <div class="panel-body"><pre><?php echo $json;?></pre></div>
    </div>
<?php endif;?>


<div class="form-group">
    <button class="btn btn-block btn-lg submit_button" type="submit">Submit</button>
</div>
<?php echo $this->form()->closeTag(); ?>
</form>