<div id="form"></div>
<button id="run-btn" type="button" class="btn btn-primary btn-xlarge center-block">Tell me what is cooking tonight</button>

<div class="modal fade" id="answerModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 class="modal-title">What is cooking tonight?</h2>
            </div>
            <div class="modal-body"></div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

            </div>
        </div>
    </div>
</div><!--end of modal-->
<script>

    var AjaxForm = function() {

        this.url = arguments[0];
        this.wrapper = (arguments[1]!==undefined) ? arguments[1] : '#form';
        this.form = (arguments[2]!==undefined) ? arguments[2] : '#frmUpload';

        this.options = {
            target: this.wrapper,
            success: $.proxy(this.action, this)
        };
        this.init();
    };

    AjaxForm.prototype = {

        init: function() {
            $(this.wrapper).load(this.url + '?'+Math.random(), $.proxy(this.action, this));
            this.initRunBtn();
        },
        action: function () {
            $(this.form).ajaxForm(this.options);
            if ($('.js-uploaded-file').length == 2) {
                $('#run-btn').removeClass('disabled');
            }  else {
                $('#run-btn').addClass('disabled');
            }
        },

        initRunBtn: function() {t
            $('#run-btn').click(function(e) {
                e.preventDefault();

                if ($(this).hasClass('disabled')) {
                    return false;
                }

                $.get('/newscorp/answer.php', function(data) {

                    $('#answerModal').find('.modal-body').text(data);
                    $('#answerModal').modal();
                });

            });
        }
    };

var ajaxForm = new AjaxForm('/newscorp/public/api/index/form');
</script>